name: package_chat_pie
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  plugin_platform_interface: ^2.0.2
  piesocket_channels: ^1.0.2
  pull_to_refresh: ^2.0.0
  flutter_keyboard_visibility: ^5.4.0
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  logger: ^2.0.2+1
  equatable: ^2.0.5
  scrollable_positioned_list: ^0.3.8
  cached_network_image: ^3.2.2
  shimmer: ^3.0.0
  # chewie: ^1.7.4
  video_player: ^2.7.0
  photo_view: ^0.14.0
  extended_image: ^6.3.2
  mime: ^1.0.4
  video_thumbnail: ^0.5.3
  intl: ^0.18.0
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  flutter_flavorizr: ^2.1.3
  injectable_generator: ^1.5.4
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0
  shared_preferences: ^2.2.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.package_chat_pie
        pluginClass: PackageChatPiePlugin
      ios:
        pluginClass: PackageChatPiePlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
